### ISSUE TITLE
[Deprecated] this.pickFiles is deprecated warning for ember CLI 0.2.3

### ISSUE THREAD

**Issue by amhasler** [tsharman/ember-cli-neat#1]
New installation of ember-cli-neat addon for ember CLI 0.2.3 project results in the following on server start: 
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-neat]

**Comment by tsharman** [comment]
Fixed here: https://github.com/tsharman/ember-cli-neat/pull/3
